### ISSUE TITLE
Invalid URLs

### ISSUE THREAD

**Issue by workergnome** [american-art/acm#5] opened 2017-01-10 13:58 UTC
If I go to, say, <http://data.americanartcollaborative.org/page/acm/object/98955>, I get the error:

> HTTP Status 500 - rethrew: HttpException: 500 Exception while writing the response model: Only well-formed absolute URIrefs can be included in RDF/XML output: <http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.98955]> Code: 0/ILLEGAL_CHARACTER in FRAGMENT: The character violates the grammar rules for URIs/IRIs.

**Comment by KatherineMoloney** [comment] 2017-01-10 15:09
So the illegal character stems from the museum's URI?

**Comment by workergnome** [comment] 2017-01-10 15:55
Technically, I don't believe that `[` or `]` can be used in URLs.  

(http://stackoverflow.com/questions/40568/are-square-brackets-permitted-in-urls)

**Comment by KatherineMoloney** [comment] 2017-01-10 17:32
I don't know where the brackets originated. I'm looking at the xml data uploaded and don't see any brackets. Do you know why this is happening?

**Comment by workergnome** [comment] 2017-01-10 18:08
If I look at the uploaded file <https://raw.githubusercontent.com/american-art/acm/master/ObjectData/AAC_AmonCarter_ObjectData.xml>, I see things that look like

```
    <atom name="URL">http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.127638]</atom>
```

I'd assume that's where they're getting them from?

**Comment by sjayakum** [comment] 2017-01-10 19:33
The error because a copy of url was used as 'URI' for the url. Since this URI is not valid it is throwing exception. As a temporary fix I will change the URI to something else.

**Comment by sjayakum** [comment] 2017-01-10 19:38
I have already fixed this issue in the .ttl file in my previous commit. The data and model in the server is not refreshed with the latest one. As @mit2nil  isn't available today I will ask him to do it when he is back!

**Comment by KatherineMoloney** [comment] 2017-01-10 20:09
Many thanks. You folks are doing great work!

**Comment by bsnikhila** [comment] 2017-02-23 23:28
All the URLs currently in the data seem to be directed [here](http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.177173]) where I need to enter the Title or Accession Number to get the details of the object.

This is a sample URL in the data:
[http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.177173]](http://www.cartermuseum.org/imu/acm/#imu[details=ecatalogue.177173])

When I open the link and enter the accession number (P2009.3.17.2.22), the URL changes to:
[http://www.cartermuseum.org/imu/acm/#details=ecatalogue.177173](http://www.cartermuseum.org/imu/acm/#details=ecatalogue.177173)

If the URLs in the data file are modified to the correct URL, we can model them.

**Comment by KatherineMoloney** [comment] 2017-02-24 17:47
I think the problem is that the incorrect data set is being used. Because of an update to our collections database all of our URLs were changed last year. This document reflects that change: 
 https://github.com/american-art/acm/blob/master/AAC_AmonCarter_ObjectData_Updated_URIs.xml 

I realize that this was posted outside of the Objects folder and is probably the reason why it wasn’t used. Is it easier for me to go in and edit the URLs in the data file you are using rather than re-model the corrected data set?

To say I’m sorry for this interruption to your workflow seems inadequate. All I can do is offer my apologies and try to make corrections as quickly as I can. Please let me know the next step.

**Comment by bsnikhila** [comment] 2017-03-09 21:32
Oh I am sorry we have not used this file even though it has been uploaded months ago. I will immediately use the file to map URLs.

**Comment by VladimirAlexiev** [comment] 2017-03-12 15:16
I think #9 is a duplicate of this one.

**Comment by bsnikhila** [comment] 2017-04-30 21:00
The new file is used and the URLs seem to be working fine.

**Closed as completed by bsnikhila** 2017-04-30 21:00 UTC
